#![doc = "Peripheral access API for BL602 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    pub _handler: unsafe extern "C" fn(),
    pub _reserved: usize,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[no_mangle]
pub static __EXTERNAL_INTERRUPTS: [Vector; 0] = [];
#[doc = "Global register"]
pub type Glb = crate::Periph<glb::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Glb {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Glb").finish()
    }
}
#[doc = "Global register"]
pub mod glb;
#[doc = "RF control"]
pub type Rf = crate::Periph<rf::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Rf {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rf").finish()
    }
}
#[doc = "RF control"]
pub mod rf;
#[doc = "Universal DAC/ADC/ACOMP interface control"]
pub type Gpip = crate::Periph<gpip::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Gpip {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpip").finish()
    }
}
#[doc = "Universal DAC/ADC/ACOMP interface control"]
pub mod gpip;
#[doc = "SEC_DBG."]
pub type SecDbg = crate::Periph<sec_dbg::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for SecDbg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SecDbg").finish()
    }
}
#[doc = "SEC_DBG."]
pub mod sec_dbg;
#[doc = "SEC_ENG."]
pub type SecEng = crate::Periph<sec_eng::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for SecEng {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SecEng").finish()
    }
}
#[doc = "SEC_ENG."]
pub mod sec_eng;
#[doc = "TZC_SEC."]
pub type TzcSec = crate::Periph<tzc_sec::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for TzcSec {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TzcSec").finish()
    }
}
#[doc = "TZC_SEC."]
pub mod tzc_sec;
#[doc = "TZC_NSEC."]
pub type TzcNsec = crate::Periph<tzc_nsec::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for TzcNsec {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TzcNsec").finish()
    }
}
#[doc = "TZC_NSEC."]
pub mod tzc_nsec;
#[doc = "EF_DATA_0"]
pub type EfData0 = crate::Periph<ef_data_0::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for EfData0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EfData0").finish()
    }
}
#[doc = "EF_DATA_0"]
pub mod ef_data_0;
#[doc = "EF_DATA_1."]
pub type EfData1 = crate::Periph<ef_data_1::RegisterBlock, 0x4000_7080>;
impl core::fmt::Debug for EfData1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EfData1").finish()
    }
}
#[doc = "EF_DATA_1."]
pub mod ef_data_1;
#[doc = "eFuse memory control"]
pub type EfCtrl = crate::Periph<ef_ctrl::RegisterBlock, 0x4000_7800>;
impl core::fmt::Debug for EfCtrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EfCtrl").finish()
    }
}
#[doc = "eFuse memory control"]
pub mod ef_ctrl;
#[doc = "CCI."]
pub type Cci = crate::Periph<cci::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Cci {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cci").finish()
    }
}
#[doc = "CCI."]
pub mod cci;
#[doc = "Cache control"]
pub type L1c = crate::Periph<l1c::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for L1c {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("L1c").finish()
    }
}
#[doc = "Cache control"]
pub mod l1c;
#[doc = "UART0 control"]
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
#[doc = "UART0 control"]
pub mod uart0;
#[doc = "UART1 control"]
pub type Uart1 = crate::Periph<uart0::RegisterBlock, 0x4000_a100>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
#[doc = "UART1 control"]
pub use self::uart0 as uart1;
#[doc = "SPI master / slave control"]
pub type Spi = crate::Periph<spi::RegisterBlock, 0x4000_a200>;
impl core::fmt::Debug for Spi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi").finish()
    }
}
#[doc = "SPI master / slave control"]
pub mod spi;
#[doc = "I2C control"]
pub type I2c = crate::Periph<i2c::RegisterBlock, 0x4000_a300>;
impl core::fmt::Debug for I2c {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c").finish()
    }
}
#[doc = "I2C control"]
pub mod i2c;
#[doc = "Pulse width modulation control"]
pub type Pwm = crate::Periph<pwm::RegisterBlock, 0x4000_a400>;
impl core::fmt::Debug for Pwm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm").finish()
    }
}
#[doc = "Pulse width modulation control"]
pub mod pwm;
#[doc = "Timer control"]
pub type Timer = crate::Periph<timer::RegisterBlock, 0x4000_a500>;
impl core::fmt::Debug for Timer {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer").finish()
    }
}
#[doc = "Timer control"]
pub mod timer;
#[doc = "Infrared remote control"]
pub type Ir = crate::Periph<ir::RegisterBlock, 0x4000_a600>;
impl core::fmt::Debug for Ir {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ir").finish()
    }
}
#[doc = "Infrared remote control"]
pub mod ir;
#[doc = "Checksum engine"]
pub type Cks = crate::Periph<cks::RegisterBlock, 0x4000_a700>;
impl core::fmt::Debug for Cks {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cks").finish()
    }
}
#[doc = "Checksum engine"]
pub mod cks;
#[doc = "Flash control"]
pub type SfCtrl = crate::Periph<sf_ctrl::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for SfCtrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SfCtrl").finish()
    }
}
#[doc = "Flash control"]
pub mod sf_ctrl;
#[doc = "DMA control"]
pub type Dma = crate::Periph<dma::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Dma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma").finish()
    }
}
#[doc = "DMA control"]
pub mod dma;
#[doc = "Sleep control (power-down sleep)"]
pub type Pds = crate::Periph<pds::RegisterBlock, 0x4000_e000>;
impl core::fmt::Debug for Pds {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pds").finish()
    }
}
#[doc = "Sleep control (power-down sleep)"]
pub mod pds;
#[doc = "Deep Sleep Control (Hibernation)"]
pub type Hbn = crate::Periph<hbn::RegisterBlock, 0x4000_f000>;
impl core::fmt::Debug for Hbn {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Hbn").finish()
    }
}
#[doc = "Deep Sleep Control (Hibernation)"]
pub mod hbn;
#[doc = "Always-ON periherals"]
pub type Aon = crate::Periph<aon::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Aon {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aon").finish()
    }
}
#[doc = "Always-ON periherals"]
pub mod aon;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "GLB"]
    pub glb: Glb,
    #[doc = "RF"]
    pub rf: Rf,
    #[doc = "GPIP"]
    pub gpip: Gpip,
    #[doc = "SEC_DBG"]
    pub sec_dbg: SecDbg,
    #[doc = "SEC_ENG"]
    pub sec_eng: SecEng,
    #[doc = "TZC_SEC"]
    pub tzc_sec: TzcSec,
    #[doc = "TZC_NSEC"]
    pub tzc_nsec: TzcNsec,
    #[doc = "EF_DATA_0"]
    pub ef_data_0: EfData0,
    #[doc = "EF_DATA_1"]
    pub ef_data_1: EfData1,
    #[doc = "EF_CTRL"]
    pub ef_ctrl: EfCtrl,
    #[doc = "CCI"]
    pub cci: Cci,
    #[doc = "L1C"]
    pub l1c: L1c,
    #[doc = "UART0"]
    pub uart0: Uart0,
    #[doc = "UART1"]
    pub uart1: Uart1,
    #[doc = "SPI"]
    pub spi: Spi,
    #[doc = "I2C"]
    pub i2c: I2c,
    #[doc = "PWM"]
    pub pwm: Pwm,
    #[doc = "TIMER"]
    pub timer: Timer,
    #[doc = "IR"]
    pub ir: Ir,
    #[doc = "CKS"]
    pub cks: Cks,
    #[doc = "SF_CTRL"]
    pub sf_ctrl: SfCtrl,
    #[doc = "DMA"]
    pub dma: Dma,
    #[doc = "PDS"]
    pub pds: Pds,
    #[doc = "HBN"]
    pub hbn: Hbn,
    #[doc = "AON"]
    pub aon: Aon,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            glb: Glb::steal(),
            rf: Rf::steal(),
            gpip: Gpip::steal(),
            sec_dbg: SecDbg::steal(),
            sec_eng: SecEng::steal(),
            tzc_sec: TzcSec::steal(),
            tzc_nsec: TzcNsec::steal(),
            ef_data_0: EfData0::steal(),
            ef_data_1: EfData1::steal(),
            ef_ctrl: EfCtrl::steal(),
            cci: Cci::steal(),
            l1c: L1c::steal(),
            uart0: Uart0::steal(),
            uart1: Uart1::steal(),
            spi: Spi::steal(),
            i2c: I2c::steal(),
            pwm: Pwm::steal(),
            timer: Timer::steal(),
            ir: Ir::steal(),
            cks: Cks::steal(),
            sf_ctrl: SfCtrl::steal(),
            dma: Dma::steal(),
            pds: Pds::steal(),
            hbn: Hbn::steal(),
            aon: Aon::steal(),
        }
    }
}
